class AppErrorCode():
    UNREGISTERED_USER = (11, 'user name doesn\'t exist')
    DB_ERROR = (12, 'error during execution')
    REQUIRED_NAME = (13, 'name is required')
    REQUIRED_PASSWORD = (14, 'name is required')
    INVALID_NAME = (14, 'name is already registered')
    INVALID_PASSWORD = (14, 'password is incorrect')
    UNAUTHENTICATED_ACCESS = (15, 'login required')
    NO_RECORDS = (16, 'no records found')
    INVALID_DATA = (17, 'this type of data is not allowed')
    ZERO_ADD_ONS = (18, 'any one add on is a must')
